#!/usr/bin/env bash
# DEPRECATED: This script targets Azure Container Apps (ACA). ACA has been decommissioned for the
# dev environment (2026-04-09) per feature-aks-decommission-1.md. For AKS diagnostics use
# kubectl logs / kubectl exec / the openclaw-cli skill against https://paa-dev.acmeadventure.ca.
# Retained for historical reference and rollback scenarios during the prod soak period.
#
# diagnose-containerapp.sh — Capture a full diagnostic snapshot of the OpenClaw Container App.
#
# Usage:
#   bash scripts/diagnose-containerapp.sh <env>
#
#   env   Target environment: dev or prod (required)
#
# Output (git-ignored):
#   scripts/diag-<env>-<timestamp>.txt
#
# Prerequisites:
#   - Azure CLI logged in (az login) with Contributor access to the environment resource group.
#   - The containerapp extension must be installed (pre-installed in the dev container).
#
# Safety:
#   - This script never prints storage account keys, gateway tokens, or other secret values.
#   - Any downloaded config file is deleted before the script exits.
#   - Always target dev. Never run against prod unless performing an authorized incident response.
#
# Sections:
#   A — Revision list
#   B — Active revision detail
#   C — Recent console logs
#   D — System event stream
#   E — Diagnostics API: container exit events
#   F — Diagnostics API: storage mount failures
#   G — Azure Files config inspection (auth.token redacted)
#   H — Identity role assignments

set -uo pipefail

# ── Arguments ─────────────────────────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
  echo "Usage: bash scripts/diagnose-containerapp.sh <env>"
  echo "  env   Target environment, e.g. dev or prod"
  exit 1
fi

ENV="$1"

# ── Derived resource names (from Terraform locals.tf naming convention) ────────
APP_NAME="paa-${ENV}-app"
RG_NAME="paa-${ENV}-rg"
STORAGE_ACCOUNT="paa${ENV}ocstate"
KV_NAME="paa-${ENV}-kv"
IDENTITY_NAME="paa-${ENV}-id"
SHARE_NAME="openclaw-state"

# ── Output file ───────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_FILE="${SCRIPT_DIR}/diag-${ENV}-${TIMESTAMP}.txt"

# Temp config path — cleaned up on exit
TMP_CONFIG="/tmp/openclaw-diag-$$.json"

cleanup() {
  rm -f "$TMP_CONFIG"
}
trap cleanup EXIT

# ── Helpers ───────────────────────────────────────────────────────────────────

SECTION_COUNT=0

section() {
  SECTION_COUNT=$((SECTION_COUNT + 1))
  local header="──────────────────────────────────────────────────────────────────────────"
  printf "\n%s\n" "$header"
  printf "SECTION %s — %s\n" "$1" "$2"
  printf "%s\n" "$header"
}

run_cmd() {
  # Run a command, capturing stdout+stderr. Never fail the script.
  local label="$1"; shift
  printf "\n[CMD] %s\n" "$label"
  printf "$ %s\n\n" "$*"
  "$@" 2>&1 || printf "\n[WARN] Command exited non-zero (continuing)\n"
}

# ── Header ────────────────────────────────────────────────────────────────────

{

printf "OpenClaw Container App — Diagnostic Snapshot\n"
printf "Environment : %s\n" "$ENV"
printf "App         : %s\n" "$APP_NAME"
printf "Resource Grp: %s\n" "$RG_NAME"
printf "Storage Acct: %s\n" "$STORAGE_ACCOUNT"
printf "Key Vault   : %s\n" "$KV_NAME"
printf "Identity    : %s\n" "$IDENTITY_NAME"
printf "Timestamp   : %s\n" "$TIMESTAMP"
printf "Generated by: %s\n" "$(az account show --query 'user.name' -o tsv 2>/dev/null || echo 'unknown')"

# ── Pre-flight check ──────────────────────────────────────────────────────────

printf "\n[Pre-flight] Verifying active Azure login...\n"
if ! az account show &>/dev/null; then
  printf "ERROR: No active Azure login. Run 'az login' first.\n"
  exit 1
fi
printf "Subscription: %s\n" "$(az account show --query '[name, id]' -o tsv 2>/dev/null | tr '\n' '  ')"

# ── Section A — Revision list ─────────────────────────────────────────────────

section "A" "Revision list"

run_cmd "List all revisions (table)" \
  az containerapp revision list \
    --name "$APP_NAME" \
    --resource-group "$RG_NAME" \
    -o table

run_cmd "List all revisions (JSON — health, replica, traffic detail)" \
  az containerapp revision list \
    --name "$APP_NAME" \
    --resource-group "$RG_NAME" \
    --query "[].{name:name, runningState:properties.runningState, healthState:properties.healthState, replicas:properties.replicas, traffic:properties.trafficWeight, created:properties.createdTime}" \
    -o json

# ── Section B — Active revision detail ───────────────────────────────────────

section "B" "Active revision detail"

# Identify the revision with trafficWeight > 0
ACTIVE_REVISION="$(az containerapp revision list \
  --name "$APP_NAME" \
  --resource-group "$RG_NAME" \
  --query "[?properties.trafficWeight > \`0\`] | [0].name" \
  -o tsv 2>/dev/null || true)"

if [[ -z "$ACTIVE_REVISION" ]]; then
  printf "\n[WARN] Could not identify active revision (no traffic weight > 0). Picking latest.\n"
  ACTIVE_REVISION="$(az containerapp revision list \
    --name "$APP_NAME" \
    --resource-group "$RG_NAME" \
    --query "[-1].name" \
    -o tsv 2>/dev/null || true)"
fi

printf "\nActive revision: %s\n" "${ACTIVE_REVISION:-<unknown>}"

if [[ -n "${ACTIVE_REVISION:-}" ]]; then
  run_cmd "Revision detail — running state, health, failure reason" \
    az containerapp revision show \
      --name "$APP_NAME" \
      --resource-group "$RG_NAME" \
      --revision "$ACTIVE_REVISION" \
      --query "properties.{runningState:runningState, healthState:healthState, details:runningStateDetails, image:template.containers[0].image, replicas:replicas, created:createdTime}" \
      -o json
fi

# ── Section C — Recent console logs ──────────────────────────────────────────

section "C" "Recent console logs (tail 100)"

# Identify current replica name to enable per-replica log retrieval
REPLICA_NAME=""
if [[ -n "${ACTIVE_REVISION:-}" ]]; then
  REPLICA_NAME="$(az containerapp replica list \
    --name "$APP_NAME" \
    --resource-group "$RG_NAME" \
    --revision "$ACTIVE_REVISION" \
    --query "[0].name" \
    -o tsv 2>/dev/null || true)"
fi

if [[ -n "$REPLICA_NAME" ]]; then
  printf "\nReplica: %s\n" "$REPLICA_NAME"
  run_cmd "Container stdout/stderr (last 100 lines)" \
    az containerapp logs show \
      --name "$APP_NAME" \
      --resource-group "$RG_NAME" \
      --revision "$ACTIVE_REVISION" \
      --replica "$REPLICA_NAME" \
      --tail 100 \
      --follow false
else
  printf "\n[WARN] No replicas found for revision '%s'. Container may be at 0 replicas (crashed).\n" "${ACTIVE_REVISION:-unknown}"
  printf "       Console log retrieval is unavailable. Proceed to sections D and E.\n"
fi

# ── Section D — System event stream ──────────────────────────────────────────

section "D" "System event stream (last 50 controller events)"

printf "\nNOTE: This stream surfaced the PortMismatch error in the 2026-03-30 incident.\n"

run_cmd "Container App system events" \
  az containerapp logs show \
    --name "$APP_NAME" \
    --resource-group "$RG_NAME" \
    --type system \
    --tail 50 \
    --follow false \
  || printf "[WARN] System event log unavailable (may require newer CLI version or the app may be inactive).\n"

# ── Section E — Diagnostics API: container exit events ───────────────────────

section "E" "Diagnostics API — container exit events"

printf "\nNOTE: Undocumented API; results are time-windowed (may be sparse for very recent events).\n"

RESOURCE_ID="$(az containerapp show \
  --name "$APP_NAME" \
  --resource-group "$RG_NAME" \
  --query id \
  -o tsv 2>/dev/null || true)"

if [[ -n "${RESOURCE_ID:-}" ]]; then
  printf "\nResource ID: %s\n" "$RESOURCE_ID"
  run_cmd "Exit code summary, backoff-restart counts, last error type" \
    az rest \
      --method GET \
      --url "https://management.azure.com${RESOURCE_ID}/detectors/containerappscontainerexitevents?api-version=2023-05-01"
else
  printf "\n[WARN] Could not resolve Container App resource ID. Skipping diagnostics API sections.\n"
fi

# ── Section F — Diagnostics API: storage mount failures ──────────────────────

section "F" "Diagnostics API — storage mount failures"

printf "\nNOTE: A non-clean status here means the Azure Files share failed to mount.\n"

if [[ -n "${RESOURCE_ID:-}" ]]; then
  run_cmd "Azure Files mount failure status" \
    az rest \
      --method GET \
      --url "https://management.azure.com${RESOURCE_ID}/detectors/containerappsstoragemountfailures?api-version=2023-05-01"
else
  printf "\n[WARN] Resource ID unavailable. Skipping storage mount failure check.\n"
fi

# ── Section G — Azure Files config inspection ────────────────────────────────

section "G" "Azure Files config inspection (auth.token redacted)"

printf "\nSEC: The auth.token value is never printed — it is redacted in output below.\n"

STORAGE_KEY="$(az storage account keys list \
  --account-name "$STORAGE_ACCOUNT" \
  --resource-group "$RG_NAME" \
  --query "[0].value" \
  -o tsv 2>/dev/null || true)"

if [[ -z "${STORAGE_KEY:-}" ]]; then
  printf "\n[WARN] Could not retrieve storage account key for '%s'. Skipping config inspection.\n" "$STORAGE_ACCOUNT"
else
  DOWNLOAD_OK=false
  az storage file download \
    --account-name "$STORAGE_ACCOUNT" \
    --account-key "$STORAGE_KEY" \
    --share-name "$SHARE_NAME" \
    --path "openclaw.json" \
    --dest "$TMP_CONFIG" \
    --output none \
    2>&1 && DOWNLOAD_OK=true || printf "\n[WARN] Could not download openclaw.json from share '%s'.\n" "$SHARE_NAME"

  if [[ "$DOWNLOAD_OK" == "true" ]] && [[ -f "$TMP_CONFIG" ]]; then
    printf "\nopenclaw.json (auth.token redacted):\n"
    # Redact auth.token value before printing; keep all other fields intact
    python3 -c "
import json, sys
with open('$TMP_CONFIG') as f:
    cfg = json.load(f)
# Redact token at all nesting levels
def redact(obj):
    if isinstance(obj, dict):
        return {k: ('<redacted>' if k == 'token' else redact(v)) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [redact(i) for i in obj]
    return obj
print(json.dumps(redact(cfg), indent=2))
" 2>/dev/null || cat "$TMP_CONFIG" | sed 's/"token"[[:space:]]*:[[:space:]]*"[^"]*"/"token": "<redacted>"/g'
    # Immediate cleanup regardless of download success
    rm -f "$TMP_CONFIG"
    printf "\n[SEC] Local copy of openclaw.json deleted.\n"
  fi
fi

# ── Section H — Identity role assignments ────────────────────────────────────

section "H" "Identity role assignments"

PRINCIPAL_ID="$(az identity show \
  --name "$IDENTITY_NAME" \
  --resource-group "$RG_NAME" \
  --query principalId \
  -o tsv 2>/dev/null || true)"

if [[ -z "${PRINCIPAL_ID:-}" ]]; then
  printf "\n[WARN] Could not resolve principal ID for identity '%s'. Skipping role check.\n" "$IDENTITY_NAME"
else
  printf "\nManaged Identity principal ID: %s\n" "$PRINCIPAL_ID"
  run_cmd "Role assignments for Managed Identity (all scopes)" \
    az role assignment list \
      --assignee-object-id "$PRINCIPAL_ID" \
      --all \
      --query "[].{role:roleDefinitionName, scope:scope}" \
      -o table
fi

# ── Footer ────────────────────────────────────────────────────────────────────

printf "\n══════════════════════════════════════════════════════════════════════════\n"
printf "Diagnostic snapshot complete.\n"
printf "Output file: %s\n" "$OUT_FILE"
printf "══════════════════════════════════════════════════════════════════════════\n"

} 2>&1 | tee "$OUT_FILE"

# Always exit 0 — this is a diagnostic aid, not a gate.
exit 0
