apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jh-openclaw-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CHolmesAtLVS/personal_ai_assistant.git
    targetRevision: dev
    path: workloads/dev/openclaw-jh
    helm:
      releaseName: openclaw
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-jh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: openclaw
      jsonPointers:
        - /data
